### ISSUE TITLE
add instructions for setting SP_DATA_PATH environment variable

### ISSUE THREAD

**Issue by c-zippel** [CenterOnBudget/Rcbpp#19]
perhaps in sp_*() help file or in README example? @matt-saenz

**Comment by matt-saenz** [comment]
Thanks for flagging. I initially went with environment variable `SP_DATA_PATH` because it's something I'd been using before creating the `sp_*()` functions. Rather than explaining how to set up, I think it'd be easier to just have the preexisting [`get_sp_data_path()`](https://github.com/CenterOnBudget/Rcbpp/blob/main/R/sp_data.R#L67) function construct the path itself using info on OS and username accessed via `Sys.info()`. What do you think of that approach?
